loop_m/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("users.urls")),
    path('auth/', include('rest_framework.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path

from .views import RegistrationView, LoginView, LogoutView,PostListView,PostDetailView,ChangePasswordView
from rest_framework_simplejwt import views as jwt_views

app_name = 'users'
from .import views
urlpatterns = [
    path('',views.index,name="index"),
    path('threads/',views.threads,name="threads"),
    path('exportcsv/', views.exportcsv),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/',PostListView.as_view(),name='post-list'),
    path('logout/',views.logout_view,name='logout_page'),
    path('contect_us/',views.contect,name='contect_page'),
    path('resiter/', RegistrationView.as_view(), name='register'),
    path('accounts/login', LoginView.as_view(), name='register'),
    path('accounts/logout', LogoutView.as_view(), name='register'),
    path('accounts/change-password', ChangePasswordView.as_view(), name='register'),
    path('accounts/token-refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    
]

users/models.py
import datetime
from django.contrib.auth.models import User
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.conf import settings

from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser,AbstractUser
)
from django.utils import timezone


# Create your models here
class MyUserManager(BaseUserManager):
    def create_user(self, email,  password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    name = models.CharField( max_length=50)
    roll = models.CharField( max_length=50)
    M_number = models.CharField(max_length=11)
    email = models.EmailField(
        max_length=255,
        unique=True,
    )
    date_of_birth = models.CharField( max_length=50)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    
    expiry_date = models.DateTimeField(null=True, blank=True)
    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['date_of_birth']

    def __str__(self):
        
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    @property
    def is_out_of_credits(self):
        "Is the user out  of credits?"
        return self.credits > 0
class Post(models.Model):
    author = models.CharField( max_length=50)
    body = models.TextField(max_length=200)
    
    created_on = models.DateTimeField(default=timezone.now)

class comment (models.Model):
    txt = models.TextField(max_length=201)
    created_on = models.DateTimeField(default=timezone.now)
    author = models.CharField( max_length=50)
    post =models.ForeignKey('Post', on_delete=models.CASCADE)
class Category(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
class Sub_category(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
class Product(models.Model):
    Available =(
        ('In stack','In stack'),
        ('Out of stack','Out of stack')
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    
   
    available  = models.CharField(max_length = 100,choices =Available,null ='True')
    sub_category = models.ForeignKey(Sub_category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='Ecommerce/ping')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class contect_us(models.Model):
    name = models.CharField(max_length =100)
    email = models.EmailField(max_length =100)
    subject = models.TextField(max_length =100)
    message=models.TextField(max_length =1000)
    def __str__(self):
        return self.name

users/forms.py
from django import forms
from .models import Post, comment

class PostForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
            }))

    class Meta:
        model = Post
        fields = ['body']

class CommentForm(forms.ModelForm):
    txt = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...'
            }))

    class Meta:
        model = comment
        fields = ['txt']

users/views.py
from django.shortcuts import render,redirect


from django.shortcuts import render

from rest_framework.response import  Response
from rest_framework.views import APIView
# from .utils import get_tokens_for_user

from django.views import View
from .models import Post,comment
from .forms import PostForm,CommentForm

from rest_framework import status

from rest_framework.response import  Response
from rest_framework.views import APIView
# from .utils import get_tokens_for_user

# Create your views here.
from .models import *
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import  Response
from rest_framework.views import APIView
# from .utils import get_tokens_for_user
from .serializers import RegistrationSerializer, PasswordChangeSerializer
# Create your views here.
import csv

# Create your views here.

import csv

# Create your views here.

def exportcsv(request):
    students = Product.objects.all()
    response = HttpResponse('text/csv')
    response['Content-Disposition'] = 'attachment; filename=students.csv'
    writer = csv.writer(response)
    writer.writerow(['ID', 'image', 'name', 'price', 'date'])
    studs = students.values_list('id','image', 'name', 'price', 'date')
    for std in studs:
        writer.writerow(std)
    return response
def threads(request):
    return render(request,'threads.html')
class RegistrationView(APIView):
    def post(self, request):
        serializer = RegistrationSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class LoginView(APIView):
    def post(self, request):
        if 'email' not in request.data or 'password' not in request.data:
            return Response({'msg': 'Credentials missing'}, status=status.HTTP_400_BAD_REQUEST)
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            auth_data = get_tokens_for_user(request.user)
            return Response({'msg': 'Login Success', **auth_data}, status=status.HTTP_200_OK)
        return Response({'msg': 'Invalid Credentials'}, status=status.HTTP_401_UNAUTHORIZED)


class LogoutView(APIView):
    def post(self, request):
        logout(request)
        return Response({'msg': 'Successfully Logged out'}, status=status.HTTP_200_OK)



class ChangePasswordView(APIView):
    permission_classes = [IsAuthenticated, ]

    def post(self, request):
        serializer = PasswordChangeSerializer(context={'request': request}, data=request.data)
        serializer.is_valid(raise_exception=True) #Another way to write is as in Line 17
        request.user.set_password(serializer.validated_data['new_password'])
        request.user.save()
        return Response(status=status.HTTP_204_NO_CONTENT)
from rest_framework_simplejwt.tokens import RefreshToken

def get_tokens_for_user(user):
    refresh = RefreshToken.for_user(user)

    return {
        'refresh': str(refresh),
        'access': str(refresh.access_token),
    }
def index(request):
        
        category= Category.objects.all()
        brandId = request.GET.get('brand')
        CategoryId = request.GET.get('category')
        if CategoryId:
            product = Product.objects.filter(sub_category=CategoryId).order_by('-id')
        elif brandId:
            product = Product.objects.filter(brand=brandId).order_by('-id')

        else:
            product=Product.objects.all()

        context={
            "category":category,
            
            "product":product
        }
        return render(request,'index.html',context)
def logout_view(request):
    logout(request)
    return redirect('/auth/login/')
def contect(request):
    if request.method =="POST":
        contect = contect_us(
            name = request.POST.get('name'),
            email = request.POST.get('email'),
            subject = request.POST.get('subject'),
            message = request.POST.get('message'),
        )
        contect.save()
    return render(request,'contect.html')
class PostListView( View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all().order_by('-created_on')
        form = PostForm()

        context = {
            'post_list': posts,
            'form': form,
        }

        return render(request, 'post_list.html', context)

    def post(self, request, *args, **kwargs):
        posts = Post.objects.all().order_by('-created_on')
        form = PostForm(request.POST)

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()

        context = {
            'post_list': posts,
            'form': form,
        }

        return render(request, 'post_list.html', context)
class PostDetailView( View):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm()

        comments = comment.objects.filter(post=post).order_by('-created_on')

        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }

        return render(request, 'post_detail.html', context)
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

        comments = comment.objects.filter(post=post).order_by('-created_on')

        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }

        return render(request, 'post_detail.html', context)



class LogoutView(APIView):
    def post(self, request):
        logout(request)
        return Response({'msg': 'Successfully Logged out'}, status=status.HTTP_200_OK)

users/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Loop Method</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet">
    <link href="{% static 'css/price-range.css' %}" rel="stylesheet">
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/main.css' %}" rel="stylesheet">
	<link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="/static/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="/static/images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						
						<div class="btn-group pull-right">
							<div class="btn-group">
								
								<ul class="dropdown-menu">
									
								</ul>
							</div>
							
							<div class="btn-group">
								
								
									
								</ul>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								<li><a href="/threads/"><i class="fa fa-user"></i>threads information </a></li>
								<li><a href="/accounts/register/"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="/contect_us/"><i class="fa fa-user"></i>Message</a></li>
								<li><a href="/post/"><i class="fa fa-user"></i>Post</a></li>
								
								{% if request.user.is_authenticated %}
								<li><a href="/logout/"><i class="fa fa-lock"></i> logout</a></li>
								{% else %}
								<li><a href="/auth/login/"><i class="fa fa-lock"></i> Login</a></li>

								{% endif %}
								
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
	
		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							
						</div>
						
					</div>
					<div class="col-sm-3"  >
						<form action="/search/" method="get">
						<div class="search_box pull-right">
							<input name="query"  type="text" placeholder="Search"/>
						</div>
					</form>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->
{% block body %}

{% endblock %}
    
						
		
		
	

  
    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
	<script src="{% static 'js/price-range.js' %}"></script>
    <script src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

users/templates/contect.html
{% extends 'base.html' %}
{% block body %}
</header>
<!--/header-->


        <div class="row">
            <div class="col-sm-8">
                <div class="contact-form">
                    <h2 class="title text-center">Get In Touch</h2>
                    <div class="status alert alert-success" style="display: none"></div>
                    <form id="main-contact-form" class="contact-form row" name="contact-form" method="post">
                        {% csrf_token %}
                       
                        <div class="form-group col-md-6">

                            <input type="text" name="name" class="form-control" required="required" placeholder="Name">
                        </div>
                        <div class="form-group col-md-6">
                            <input type="email" name="email" class="form-control" required="required"
                                placeholder="Email">
                        </div>
                        <div class="form-group col-md-12">
                            <input type="text" name="subject" class="form-control" required="required"
                                placeholder="Subject">
                        </div>
                        <div class="form-group col-md-12">
                            <textarea name="message" id="message" required="required" class="form-control" rows="8"
                                placeholder="Your Message Here"></textarea>
                        </div>
                        <div class="form-group col-md-12">
                            <input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
                        </div>
                    </form>
                </div>
            </div>
            

{% endblock %}

users/templates/index.html
{% extends 'base.html' %}
{% block body %}

<!--/slider-->

<section>
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<div class="left-sidebar">
					<h2>Category</h2>
					<div class="panel-group category-products" id="accordian">
						<!--category-productsr-->
						{% for cat in category %}
						<div class="panel panel-default">
							<div class="panel-heading">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#accordian" href="#{{cat.id}}">
										<span class="badge pull-right"><i class="fa fa-plus"></i></span>
										{{cat.name}}
									</a>
								</h4>
							</div> 

							<div id="{{cat.id}}" class="panel-collapse collapse">
								<div class="panel-body">
									<ul>
										{% for i in cat.sub_category_set.all %}
										<li><a href="/?category={{i.id}}">{{i.name}} </a></li>
										{% endfor %}
									</ul>
								</div>
							</div>
						</div>
						
						{% endfor %}
					</div>
					<!--/category-products-->

					<div class="brands_products">
						<!--brands_products-->
						
						<div class="brands-name">
							<ul class="nav nav-pills nav-stacked">
								
							</ul>
						</div>
					</div>
					<!--/brands_products-->

					<div class="price-range">
						<!--price-range-->
						
					</div>
					<!--/price-range-->


				</div>
			</div>

			<div class="col-sm-9 padding-right">
				<div class="features_items">
					<!--features_items-->
					<h2 class="title text-center">Features Items</h2>
					{% for p in product %}
					<div class="col-sm-4">
						<div class="product-image-wrapper">
							<div class="single-products">
								<div class="productinfo text-center">
									<img src="{{p.image.url}}" alt="" height="200" />
									<h2>₹ {{p.price}}</h2>
									<p>{{p.name}}</p>
									
								
								</div>
							</div>
							<div class="choose">
								
							</div>
						</div>
					</div>
					{% endfor %}
					
				</div>
				<!--features_items-->

						

{% endblock %}

users/templates/post_detail.html
{% load crispy_forms_tags %}
{% block content %}
<h1> Comment </h1>

<p> <a href="#"> <strong> <span> username</span> </strong>{{post.auther}} </a>

    
  </p>
  <br>
  <div><strong>massage</strong> {{post.body}}</div>
  <br>
  <div> <strong>date</strong> {{post.created_on}}</div>
  
  
  <hr>
  <div>
    <div class="container">
      <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <a href="/post/"class=" btn btn-primary"> back feed</a>
        <input type="submit" class="btn btn-success mt-3" style="color: rgb(13, 255, 0);" value="comment">
      </form>



    </div>
    <hr>
    {% for comment in comments %}
<div> <a href="#"> <strong> <span> username</span> </strong>{{comment.author}} </a></div>


{{comment.id}}
<div><strong>massage</strong> {{comment.post}}</div>

<br>
<div><strong>massage</strong> {{comment.txt}}</div>
<br>
<div> <strong>date</strong> {{comment.date}}
    {% endfor %}
{% endblock %}

users/templates/post_list.html
{% load crispy_forms_tags %}
{% block content %}
<ul>
    
   
    
    </ul>
<h1>post </h1>
<div>
    <div class="container">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            
            
            
            <input type="submit" style="color: rgb(13, 255, 0);" value="Send Message">
        </form>
        
        
        
    </div>
</div>
<div>
    {% for post in post_list %}
    <p><a style="text-decoration: none" class="text-primary" href="#">@{{ post.author }}</a> {{ post.created_on }}</p>
    <div class="d-flex flex-row">
       {{post.body}}
       
       
    </div>
    {{post.id}}
   
    

        
</div>
    <hr>
    {% endfor %}

{% endblock %}

users/templates/threads.html
{% extends 'base.html' %}
{% block body %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Threads Info</title>
</head>
<body>
    <center>
    <H1 style="color: blue;" >Threads Informations </H1>
</center>
<center>
<p> Threads is a separate flow of execution.
    Every Threads has a task.
    Python threading allows you to have different parts of your program run concurrently and can simplify your design. If you’ve got some experience in Python and want to speed up your program using threads, then this tutorial is for you!
</p>
</center>
<center>
    <H1 style="color: blue;" >Multithreading Informations </H1>
</center>
<center>
  <h4> Using Multiple threads in program or process</h4>
  <p>The main important applications areas of multi threading are</p>
  <details>
    * Multimedia Graphic
    * Animations
    * Video Games
    * web Servers
    * Applications Server
  </details>
</center>
  <center>
    <H1 style="color: blue;" >Main Threads Informations </H1>
</center>
<center>
 <p> When we  start any python program. one threads beging running
    immediatcly , which is called main Threads of that program create by pvm.
    The main thread is create automatically when your program is started
 </p>
</center>

</body>
</html>

{% endblock %}